In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
reviews = ["nice food",
          "amazing restaurant",
           "too good",
          "Just loved it",
          "will go again",
           "horrible food",
          "never go there",
          "poor services",
           "poor quality",
          "needs improvement"]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
type(reviews)
for i in reviews:
    print(i)

nice food
amazing restaurant
too good
Just loved it
will go again
horrible food
never go there
poor services
poor quality
needs improvement


In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
# from sklearn.preprocessing import one_hot

In [5]:
one_hot("amazingrestaurbjxjdkdjdhidheidheihdiihhidhiesdbchdvchkvdhcadbkckcbkucvbcvsdyhkvhkcvdjbcbssnt bxsh uxb", 5)

[4, 3, 4]

In [6]:
# dir(tf.keras.preprocessing.sequence)

In [7]:
vocab_size = 30
encoded_reviews =[one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[11, 6],
 [6, 29],
 [8, 9],
 [12, 1, 11],
 [22, 26, 25],
 [9, 6],
 [24, 26, 13],
 [9, 23],
 [9, 25],
 [20, 28]]

In [8]:
max_length = 3

padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
padded_reviews

array([[11,  6,  0],
       [ 6, 29,  0],
       [ 8,  9,  0],
       [12,  1, 11],
       [22, 26, 25],
       [ 9,  6,  0],
       [24, 26, 13],
       [ 9, 23,  0],
       [ 9, 25,  0],
       [20, 28,  0]], dtype=int32)

In [9]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length = max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [10]:
X = padded_reviews
y = sentiment

In [11]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              120       
_________________________________________________________________
flatten (Flatten)            (None, 12)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 13        
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [53]:
from tensorflow.keras.utils import plot_model

In [54]:
plot_model(model)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [57]:
model.fit(X, y, verbose = 2, epochs = 50)

Epoch 1/50
1/1 - 0s - loss: 0.6969 - accuracy: 0.5000
Epoch 2/50
1/1 - 0s - loss: 0.6956 - accuracy: 0.6000
Epoch 3/50
1/1 - 0s - loss: 0.6943 - accuracy: 0.6000
Epoch 4/50
1/1 - 0s - loss: 0.6930 - accuracy: 0.6000
Epoch 5/50
1/1 - 0s - loss: 0.6917 - accuracy: 0.6000
Epoch 6/50
1/1 - 0s - loss: 0.6903 - accuracy: 0.6000
Epoch 7/50
1/1 - 0s - loss: 0.6890 - accuracy: 0.6000
Epoch 8/50
1/1 - 0s - loss: 0.6877 - accuracy: 0.6000
Epoch 9/50
1/1 - 0s - loss: 0.6864 - accuracy: 0.6000
Epoch 10/50
1/1 - 0s - loss: 0.6851 - accuracy: 0.6000
Epoch 11/50
1/1 - 0s - loss: 0.6838 - accuracy: 0.6000
Epoch 12/50
1/1 - 0s - loss: 0.6825 - accuracy: 0.6000
Epoch 13/50
1/1 - 0s - loss: 0.6812 - accuracy: 0.6000
Epoch 14/50
1/1 - 0s - loss: 0.6799 - accuracy: 0.6000
Epoch 15/50
1/1 - 0s - loss: 0.6786 - accuracy: 0.6000
Epoch 16/50
1/1 - 0s - loss: 0.6773 - accuracy: 0.9000
Epoch 17/50
1/1 - 0s - loss: 0.6760 - accuracy: 0.9000
Epoch 18/50
1/1 - 0s - loss: 0.6747 - accuracy: 0.9000
Epoch 19/50
1/1 - 0

In [58]:
loss, accuracy = model.evaluate(X, y)

1/1 [==============================] - 0s 332ms/step - loss: 0.6286 - accuracy: 1.0000


In [60]:
weights = model.get_layer('embedding').get_weights()[0]

In [61]:
len(weights)

30

In [67]:
weights[7], weights[8]

(array([0.02696124, 0.04967841, 0.0087657 , 0.04852789], dtype=float32),
 array([ 0.01712811, -0.04825655,  0.01921607, -0.01167389], dtype=float32))

In [1]:
import ntlk

ModuleNotFoundError: No module named 'ntlk'

In [ ]:
n