In [108]:
import numpy as np
import torch
import torch.nn.functional as F
import torch.nn as nn
# from torchvision import transforms, datasets
from torch.utils.data import DataLoader, TensorDataset

In [57]:
X = np.random.randn(50,3).astype('float32')
y = np.arange(50).astype('float32')

In [58]:
X.shape, y.shape

((50, 3), (50,))

In [59]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)

In [60]:
X.dtype

torch.float32

In [61]:
model = nn.Linear(in_features=3, out_features=1)

In [62]:
model.bias

Parameter containing:
tensor([-0.5483], requires_grad=True)

In [63]:
model.weight

Parameter containing:
tensor([[ 0.3935,  0.1300, -0.5389]], requires_grad=True)

In [64]:
X.shape

torch.Size([50, 3])

In [65]:
data = TensorDataset(X, y)

In [66]:
dataloader = DataLoader(data, batch_size = 5, shuffle = True)

In [67]:
for d in dataloader:
    print(d)
    break

[tensor([[-0.8461, -1.2546, -0.0845],
        [-2.4318,  0.6787, -0.0854],
        [-2.5484,  1.1510, -0.3819],
        [-0.3490, -1.2392,  1.5621],
        [-0.3439, -0.9672,  0.1829]]), tensor([32.,  9.,  8., 19., 36.])]


In [69]:
model.parameters()

<generator object Module.parameters at 0x7f2bbeac7d60>

In [71]:
preds = model(X)

In [73]:
preds.shape

torch.Size([50, 1])

In [77]:
loss_fn = F.mse_loss

loss = (model(X), y)
opt = torch.optim.SGD(model.parameters(), lr = 0.001)

In [105]:
def fit(num_epochs, model, opt, loss_f):
    for epoch in range(num_epochs):
        for dx, dy in dataloader:
            preds = model(X)
            loss = loss_f(preds, dy)
            
            loss.backward()
            opt.step()
            opt.zero_grad()
        print("epoch {} / {} loss {}".format(epoch, num_epochs, loss))
    

In [106]:
fit(20, model, opt, loss_fn)

epoch 0 / 20 loss 580.846435546875
epoch 1 / 20 loss 839.104736328125
epoch 2 / 20 loss 972.3665771484375
epoch 3 / 20 loss 632.6762084960938
epoch 4 / 20 loss 240.6192626953125
epoch 5 / 20 loss 1294.6246337890625
epoch 6 / 20 loss 726.031005859375
epoch 7 / 20 loss 374.32513427734375
epoch 8 / 20 loss 913.349853515625
epoch 9 / 20 loss 991.7652587890625
epoch 10 / 20 loss 192.74310302734375
epoch 11 / 20 loss 939.0581665039062
epoch 12 / 20 loss 536.3690795898438
epoch 13 / 20 loss 586.2606811523438
epoch 14 / 20 loss 672.8619384765625
epoch 15 / 20 loss 431.0632019042969
epoch 16 / 20 loss 539.615478515625
epoch 17 / 20 loss 764.2916259765625
epoch 18 / 20 loss 313.2334899902344
epoch 19 / 20 loss 685.7833251953125


<ipython-input-105-4270ef452f31>:5: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([50, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = loss_f(preds, dy)


In [85]:
[w, b] = model.parameters()

In [86]:
w

Parameter containing:
tensor([[-0.2103, -0.5270, -0.8199]], requires_grad=True)

In [87]:
b

Parameter containing:
tensor([7.6947], requires_grad=True)

In [88]:
b.backward()

In [89]:
b

Parameter containing:
tensor([7.6947], requires_grad=True)

In [101]:
class Linear(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Linear, self).__init__()
        
        # define the model
        self.lin = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        return self.lin(x)
        

In [102]:
model = Linear(3, 1)

In [103]:
??model

In [104]:
model(X)

tensor([[-0.1958],
        [-0.0582],
        [ 1.2346],
        [-0.0751],
        [-0.0619],
        [ 0.0379],
        [ 2.1040],
        [ 0.1666],
        [ 0.8865],
        [ 1.1963],
        [ 2.2112],
        [ 0.7989],
        [ 1.1163],
        [ 1.8148],
        [ 0.0936],
        [ 1.0000],
        [ 0.2132],
        [-0.0737],
        [ 0.1083],
        [ 2.0036],
        [ 1.5071],
        [-0.0634],
        [ 0.4300],
        [ 0.8826],
        [-0.9491],
        [-0.1594],
        [-0.2819],
        [-0.1745],
        [ 1.8935],
        [ 1.0469],
        [ 0.9058],
        [ 0.5774],
        [ 1.3670],
        [ 0.3633],
        [-0.3624],
        [ 0.0630],
        [ 1.1683],
        [ 0.6290],
        [-0.3561],
        [ 0.5396],
        [-0.4981],
        [-0.1064],
        [-0.1042],
        [ 0.8077],
        [ 0.5297],
        [ 0.5418],
        [ 1.2165],
        [ 0.7751],
        [ 0.6705],
        [-0.4451]], grad_fn=<AddmmBackward>)