In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# create features

X = np.array([-7.0, -4.0, -1.0, 2.0,5.0,8.0,11.0,14.0])

#  create labels

y = np.array([3.0,6.0,9.0,12.0,15.0,18.0,21.0,24.0])
# plt.scatter(X,y)

In [4]:
X+10

array([ 3.,  6.,  9., 12., 15., 18., 21., 24.])

In [5]:
y == X+10

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [6]:
#  Inpout and output shapes
input_shape = X[0].shape
output_shape = y[0].shape


input_shape, output_shape

((), ())

In [7]:
#  turn our numpy arays init tendors
X = tf.constant(X)
y = tf.constant(y)

input_shape = X[0].shape
output_shape = y[0].shape
input_shape, output_shape

(TensorShape([]), TensorShape([]))

## steps in modelling with tensorflow

1. Crteating a mode, layers and hidden layers of the deep learning model
2. compilling a model - dfeine the loss function (in other words , the function which tells )
3. fit the data to the model

In [8]:
# set the random seed 
tf.random.set_seed(42)

#  create a model using sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

#  compile
model.compile(loss = tf.keras.losses.mse, optimizer = tf.keras.optimizers.SGD(), metrics = ["mae"])

#  fit the model

model.fit(X, y, epochs = 5, verbose= 2)

Epoch 1/5
1/1 - 1s - loss: 141.0943 - mae: 11.5048
Epoch 2/5
1/1 - 0s - loss: 78.3486 - mae: 7.3274
Epoch 3/5
1/1 - 0s - loss: 73.6895 - mae: 7.7554
Epoch 4/5
1/1 - 0s - loss: 71.2925 - mae: 7.4710
Epoch 5/5
1/1 - 0s - loss: 69.0506 - mae: 7.3841


In [9]:
#  make a prediction

X, y

(<tf.Tensor: shape=(8,), dtype=float64, numpy=array([-7., -4., -1.,  2.,  5.,  8., 11., 14.])>,
 <tf.Tensor: shape=(8,), dtype=float64, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.])>)

In [21]:
#  ttry and make a prediction

c = model.predict([17.0])
c[0][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

## imporve our model
## we can imporve a model by altering the stepss we took to crate the model
1. we might need to addd more layers, increase the number of idden layers, change the activation function for each layer

2. **compiling a model*** -here we mught need to change ethe loss 