we are going to cover***
- Introduction to tensorflow
- getting information out of tesors
- Manipulating tensors
- Tensors and numpy
- Using @tf.funtion
- Using gpus
- Exercise

In [1]:
import tensorflow as tf

print(tf.__version__)

2.5.0


In [5]:
#  creatig tensors using tf.constant()

scalar = tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#check the number of dimensions

scalar.ndim

0

In [7]:
# create a vector
vector = tf.constant([4,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [8]:
 vector.ndim

1

In [11]:
matrix = tf.constant([[1,2,3],[1,2,3]])

matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [12]:
matrix.ndim

2

In [13]:
# create another matrix

another_tensor = tf.constant([[10,7],[3,4],[7,8]], dtype = tf.float16)

In [14]:
another_tensor.ndim

2

In [16]:
another_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 7.,  8.]], dtype=float16)>

In [18]:
# what do you think the number of dimension is for anther matrix

another_tensor.ndim

2

In [26]:
tensor= tf.constant([[[1,2,3],[4,5,6]],[[6,7,8],[3,4,5]]])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [3, 4, 5]]], dtype=int32)>

In [27]:
tensor.ndim

3

## create tensors with `tf.Variable`

In [2]:
# changeable tensor
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [3]:
# try to change one of the elements in chaneable tensor
# not working

changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# try .assign()

changeable_tensor[0].assign(7)
# changeable_tensor

In [4]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# creating random tensors

In [5]:
random_1  = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2_ = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [6]:
random_3 = tf.random.Generator.from_seed(42)

random_3 = random_3.normal(shape = (5,4))
random_3

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085]],
      dtype=float32)>

In [7]:
# shuffle a tensor
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [8]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [9]:
# shuffle our non shuffled tensor
tf.random.shuffle(not_shuffled, seed = 9)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [10]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [11]:
tf.random.set_seed(10)

tf.random.shuffle(not_shuffled, seed = 10)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [12]:
rank_4 = tf.zeros(shape = (4,3,4, 10))

In [13]:
rank_4

<tf.Tensor: shape=(4, 3, 4, 10), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0.,

In [14]:
rank_4.ndim

4

In [15]:
rank_4[0]

<tf.Tensor: shape=(3, 4, 10), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [16]:
tf.size(rank_4)

<tf.Tensor: shape=(), dtype=int32, numpy=480>

In [17]:
tf.random.set_seed(1)

rank_2 = tf.random.normal(shape = (3,2), seed = 1)
rank_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.28183395,  2.3878284 ],
       [ 2.2804048 , -0.308662  ],
       [-0.4475815 , -0.807146  ]], dtype=float32)>

In [18]:
# create an extra axis at the beginning
rank_2 = rank_2[tf.newaxis,...]

rank_2 = rank_2[...,tf.newaxis]

In [19]:
rank_2

<tf.Tensor: shape=(1, 3, 2, 1), dtype=float32, numpy=
array([[[[ 0.28183395],
         [ 2.3878284 ]],

        [[ 2.2804048 ],
         [-0.308662  ]],

        [[-0.4475815 ],
         [-0.807146  ]]]], dtype=float32)>

In [20]:
# alternative to tf.newaxis

tf.expand_dims(rank_2, axis = 0) # -1 means expand the last axis, 0 expand the zero axis

<tf.Tensor: shape=(1, 1, 3, 2, 1), dtype=float32, numpy=
array([[[[[ 0.28183395],
          [ 2.3878284 ]],

         [[ 2.2804048 ],
          [-0.308662  ]],

         [[-0.4475815 ],
          [-0.807146  ]]]]], dtype=float32)>

## Manipulating tensors

In [21]:
# add values using basic addition opertaor

tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [22]:
# the original tensor is unchanged
# the only way to change is

tensor = tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [23]:
tensor2 = tf.constant([[3,4,5],[6,7,8]])
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [24]:
# proof that the tensor doesn't change
tensor2 + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 14, 15],
       [16, 17, 18]], dtype=int32)>

In [25]:
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [26]:
# multiplication

tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [27]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [28]:
# we can use the tensoflow builtin function tf.ma

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [29]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix multiplication

In [30]:
#  elementwise multiplicaton
print(tensor)
tensor*tensor

tensor

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [31]:
# in machine learming matrix multiplication is a mmost common operation

# matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [32]:
# matrix multiplication witth python we use "@"
tensor@tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [33]:
# create a tensor

In [34]:
#  let's change the shape

tf.reshape(tensor, shape = (1,4))
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [35]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [17, 14]], dtype=int32)>

In [36]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

## The dot product
- Matrix multiplication is also reffered to as dot product
- `tf.matmul()`
- `tf.tensordot()`

In [37]:
X = tf.constant([[1,2],[3,4],[5,6]])
y = tf.constant([[7,8],[9,10],[11,12]])
X, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [38]:
#  Peform the dot produuct on X and y , This requires X or y to be transppose
tf.tensordot(tf.transpose(X), y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [39]:
tf.matmul(tf.transpose(X),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [40]:
c = tf.Variable([9907987.8897898087776])
c

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([9907988.], dtype=float32)>

In [41]:
# change from float32 to float26; called reduced precision
c = tf.constant([7,10])
b  = tf.cast(c, dtype = tf.float32)
b.dtype

tf.float32

In [42]:
# change from int32 to float32
g = tf.constant([3,5])
g = tf.cast(g, dtype = tf.float16)
g.dtype

tf.float16

## Aggregating tensors

Agregating tensors = condensing them from multipe values down to a smaller amoubt of values

In [43]:
#  Get the absolute values
d = tf.constant([--7,-10])

In [44]:
# get the absolute value
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### lets's vo through the d==following forms of aggregation
- get thew minimum
- get the maximum
- get the mean of a tensor

In [45]:
import numpy as np

In [46]:
#  create a random tensor with vales btw zero and hundred

e = tf.constant(np.random.randint(0,100, size = 50))

In [47]:
e.dtype

tf.int64

In [48]:
e.shape

TensorShape([50])

In [49]:
e.ndim

1

In [50]:
tf.size(e)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [51]:
#  Find the min
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [52]:
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([66, 74, 52, 71, 29,  2, 15, 81, 36, 90, 74, 87, 64,  4, 78,  0, 95,
       56, 13, 67, 40, 40, 41, 57, 78, 74, 88, 92, 16, 74, 72, 45, 28, 41,
       10, 45, 16,  3, 26,  9, 86, 98, 36, 36, 39,  6, 62, 10, 44, 21])>

In [53]:
#  find the max

tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [54]:
#  find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [55]:
#  find the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2387>

********find the variance and std of our e tensor in our e tensor**

In [56]:
import tensorflow_probability as tfp

ModuleNotFoundError: No module named 'tensorflow_probability'

In [57]:
#  wont work
tf.reduce_variance(e)

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [58]:
#  find the variance

tfp.stats.variance(e)


NameError: name 'tfp' is not defined

In [59]:
#  variance
tf.math.reduce_variance(tf.cast(e, dtype = tf.float32 ))

<tf.Tensor: shape=(), dtype=float32, numpy=852.59235>

In [60]:
#  Find the std
tf.math.reduce_std(tf.cast(e,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.199184>

*** Find the positional maximum and minimum of a tensor***

In [61]:
#  create a new tensor 
tf.random.set_seed(8)

f = tf.random.uniform(shape = [50], seed = 8)
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.35557675, 0.04640651, 0.4299122 , 0.06953716, 0.6977596 ,
       0.14093244, 0.27604806, 0.0883975 , 0.26191568, 0.8146517 ,
       0.64363575, 0.47054517, 0.15543795, 0.7185929 , 0.09850168,
       0.31211555, 0.33725405, 0.7131622 , 0.24237263, 0.7147795 ,
       0.28028512, 0.37993717, 0.3871237 , 0.658684  , 0.9236132 ,
       0.69641876, 0.05440629, 0.8219104 , 0.71466625, 0.5205053 ,
       0.698874  , 0.50196886, 0.73813415, 0.8705375 , 0.05154383,
       0.22742355, 0.12300825, 0.90719306, 0.36541235, 0.5586027 ,
       0.07865596, 0.2738738 , 0.11129963, 0.33042562, 0.9850422 ,
       0.1550417 , 0.07874548, 0.55022097, 0.444548  , 0.17932427],
      dtype=float32)>

In [62]:
#  find the positional max 
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [63]:
#  index on our largest value posision
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9850422>

In [64]:
#  find the max value of f
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9850422>

In [65]:
# check for equality
assert f[tf.argmax(f)] == tf.reduce_max(f)

In [66]:
# find the pos mnimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [67]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.046406507>

In [68]:
### Squezing a tensor (removing all the single dimensions)

g = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.3654405 , 0.33800936, 0.58849275, 0.38295197, 0.03967929,
          0.7868792 , 0.86955893, 0.41382527, 0.57872975, 0.4035679 ,
          0.3268162 , 0.7909788 , 0.84162605, 0.5040089 , 0.64847255,
          0.855749  , 0.0896858 , 0.5986353 , 0.27876437, 0.10400105,
          0.5209594 , 0.12287998, 0.82404053, 0.12953532, 0.43485928,
          0.45827782, 0.3759321 , 0.5020915 , 0.06105852, 0.6359985 ,
          0.68580365, 0.22726703, 0.8691689 , 0.71161187, 0.38431954,
          0.58297825, 0.5733441 , 0.3017658 , 0.26428688, 0.17978573,
          0.17696989, 0.29042315, 0.77083623, 0.14604008, 0.8028511 ,
          0.85627604, 0.7079444 , 0.4913106 , 0.7064265 , 0.6764469 ]]]],
      dtype=float32)>

In [69]:
g.ndim

4

In [70]:
g.shape

TensorShape([1, 1, 1, 50])

In [71]:
g_squezed = tf.squeeze(g)
g_squezed.shape

TensorShape([50])

In [72]:
g_squezed.ndim

1

### One hot encoding

In [73]:
#   create a list of indexes

some_list = [0,2,3,4,5]
tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [74]:
#  pecify xcustom values for one one hot encode
tf.one_hot(some_list, depth = 5, on_value = "Range lexus bentley lamborghini", off_value = "mercedese bmw dodge audi royce")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Range lexus bentley lamborghini',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce'],
       [b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'Range lexus bentley lamborghini',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce'],
       [b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'Range lexus bentley lamborghini',
        b'mercedese bmw dodge audi royce'],
       [b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',
        b'Range lexus bentley lamborghini'],
       [b'mercedese bmw dodge audi royce',
        b'mercedese bmw dodge audi royce',

### a few common math operations


In [75]:
#  create a new tensor

h = tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [77]:
tf.sqrt(tf.cast(h, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [78]:
#  find the log
tf.math.log(tf.cast(h, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### tensors and numpy

In [79]:
# tensorfow interacts beatifully with numpy array?

j = tf.constant(np.array([2.,4,6]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [80]:
# converte back to our nnumpy array
np.array(j), type(np.array(j))

(array([2., 4., 6.]), numpy.ndarray)

In [81]:
# converte a tensor  j to a nummpy array
j.numpy(), type(j.numpy())

(array([2., 4., 6.]), numpy.ndarray)

In [82]:
j = tf.constant([3.])
j.numpy()[0]

3.0

In [83]:
#  default types of each are different
numpy_j = tf.constant(np.array([4.,7.]))
tensor_j = tf.constant([4.,7.])
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)